package Boundary.Carrello;

import Boundary.DTO.CarrelloDTO;
import Boundary.DTO.ProductDTO;
import Boundary.DTO.RigaCarrelloDTO;
import Controller.CarrelloController;
import Entity.client.RigaCarrello;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class panelProdotti {

    private JPanel panel1;
    private JLabel descrizione;
    private JLabel categoria;
    private JLabel prezzo;
    private JLabel quantita;
    private JButton buttonPiu;
    private JLabel image;
    private JButton buttonCestino;
    private JLabel nome;

    private RigaCarrelloDTO rigaDTO;
    private CarrelloDTO carrelloDTO;
    private CarrelloController controller;
    private MainCarrello mainCarrello;

    public panelProdotti(RigaCarrelloDTO rigaDTO, CarrelloController controller, CarrelloDTO carrelloDTO, MainCarrello mainCarrello) {
        $$$setupUI$$$();
        this.rigaDTO = rigaDTO;
        this.controller = controller;
        this.carrelloDTO = carrelloDTO;
        this.mainCarrello = mainCarrello;

        popolaCampi();

        buttonCestino.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                buttonElimina();

            }
        });
        buttonPiu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buttonAggiungi();
            }
        });
    }

    private void popolaCampi() {
        nome.setText(rigaDTO.getProductDTO().getNome());
        descrizione.setText(rigaDTO.getProductDTO().getDescrizione());
        categoria.setText(rigaDTO.getProductDTO().getCategoria());
        prezzo.setText(rigaDTO.getPrezzoTotaleRiga() + " €");
        quantita.setText("Quantità: " + rigaDTO.getQuantita());

    }


    private void buttonAggiungi() {
        long id = rigaDTO.getProductDTO().getId();
        controller.aumentaQuantita(carrelloDTO, id);
        mainCarrello.refresh();
    }

    private void buttonElimina() {
        long id = rigaDTO.getProductDTO().getId();
        controller.eliminaProdotto(carrelloDTO, id);
        mainCarrello.refresh();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16776961)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-3025959)));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(7, 5, new Insets(0, 0, 30, 0), -1, -1));
        panel2.setBackground(new Color(-1));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 3, false));
        final Spacer spacer2 = new Spacer();
        panel2.add(spacer2, new GridConstraints(1, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 3, false));
        final Spacer spacer3 = new Spacer();
        panel2.add(spacer3, new GridConstraints(0, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 3, false));
        prezzo = new JLabel();
        prezzo.setText("Prezzo");
        panel2.add(prezzo, new GridConstraints(6, 1, 1, 3, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        quantita = new JLabel();
        quantita.setText("Quantità");
        panel2.add(quantita, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        descrizione = new JLabel();
        descrizione.setText("Descrizione");
        panel2.add(descrizione, new GridConstraints(4, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        categoria = new JLabel();
        categoria.setText("Categoria");
        panel2.add(categoria, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        image = new JLabel();
        image.setText("Label");
        panel2.add(image, new GridConstraints(1, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonPiu.setBackground(new Color(-1));
        buttonPiu.setBorderPainted(false);
        Font buttonPiuFont = this.$$$getFont$$$("Arial Black", -1, 18, buttonPiu.getFont());
        if (buttonPiuFont != null) buttonPiu.setFont(buttonPiuFont);
        buttonPiu.setHideActionText(false);
        buttonPiu.setText("+");
        panel2.add(buttonPiu, new GridConstraints(5, 3, 1, 2, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(20, 20), null, 0, false));
        buttonCestino = new JButton();
        buttonCestino.setBackground(new Color(-1));
        buttonCestino.setBorderPainted(false);
        Font buttonCestinoFont = this.$$$getFont$$$("Arial Black", -1, 14, buttonCestino.getFont());
        if (buttonCestinoFont != null) buttonCestino.setFont(buttonCestinoFont);
        buttonCestino.setText("ELIMINA");
        panel2.add(buttonCestino, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(20, 20), null, 0, false));
        nome = new JLabel();
        nome.setText("NOME");
        panel2.add(nome, new GridConstraints(3, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void createUIComponents() {
        buttonPiu = new JButton();
    }


    public JPanel getPanel() {
        return panel1;
    }
}