package Boundary;

import Controller.CarrelloController;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class ProductCarrello {
    private JPanel panel1;
    private JPanel mainPanel;
    private JLabel nome;
    private JLabel descrizione;
    private JButton ButtonIncrementaQta;
    private JLabel image;
    private JButton ButtonElimina;
    private JLabel prezzo;
    private JLabel quantita;

    CarrelloController  carrelloController = new CarrelloController();

    private void createUIComponents() {
        // TODO: place custom component creation code here
        $$$setupUI$$$();

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(6, 6, new Insets(30, 20, 30, 20), -1, -1));
        mainPanel.setBackground(new Color(-1));
        panel1.add(mainPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(0, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        descrizione = new JLabel();
        descrizione.setText("Descrizione");
        mainPanel.add(descrizione, new GridConstraints(3, 0, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nome = new JLabel();
        nome.setText("Nome");
        mainPanel.add(nome, new GridConstraints(2, 0, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ButtonIncrementaQta = new JButton();
        ButtonIncrementaQta.setBackground(new Color(-1));
        ButtonIncrementaQta.setBorderPainted(false);
        Font ButtonIncrementaQtaFont = this.$$$getFont$$$(null, -1, 24, ButtonIncrementaQta.getFont());
        if (ButtonIncrementaQtaFont != null) ButtonIncrementaQta.setFont(ButtonIncrementaQtaFont);
        ButtonIncrementaQta.setText("+");
        mainPanel.add(ButtonIncrementaQta, new GridConstraints(4, 4, 1, 2, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 50), new Dimension(100, 50), new Dimension(100, 50), 0, false));
        image = new JLabel();
        image.setText("image");
        mainPanel.add(image, new GridConstraints(1, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        mainPanel.add(spacer2, new GridConstraints(1, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        ButtonElimina = new JButton();
        ButtonElimina.setBackground(new Color(-1));
        ButtonElimina.setBorderPainted(false);
        Font ButtonEliminaFont = this.$$$getFont$$$(null, -1, 22, ButtonElimina.getFont());
        if (ButtonEliminaFont != null) ButtonElimina.setFont(ButtonEliminaFont);
        ButtonElimina.setText("\uD83D\uDDD1\uFE0F");
        mainPanel.add(ButtonElimina, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 50), new Dimension(100, 50), new Dimension(100, 50), 0, false));
        prezzo = new JLabel();
        Font prezzoFont = this.$$$getFont$$$("Arial Black", -1, 18, prezzo.getFont());
        if (prezzoFont != null) prezzo.setFont(prezzoFont);
        prezzo.setText("PREZZO");
        mainPanel.add(prezzo, new GridConstraints(5, 1, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        quantita = new JLabel();
        quantita.setText("Quantità");
        mainPanel.add(quantita, new GridConstraints(4, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
